"""
Mock Server Service - Offline API testing without real calls.

Generates realistic mock responses for all 15 monitored APIs
and provides offline code generation.
"""
import json
import random
import logging
from datetime import datetime, timezone
from typing import Dict, Any

logger = logging.getLogger(__name__)

MOCK_RESPONSES: Dict[str, Dict[str, Any]] = {
    "OpenWeatherMap": {
        "coord": {"lon": -0.1257, "lat": 51.5085},
        "weather": [{"id": 801, "main": "Clouds", "description": "few clouds"}],
        "main": {"temp": 285.32, "feels_like": 284.2, "pressure": 1023, "humidity": 72},
        "wind": {"speed": 4.63, "deg": 250},
        "name": "London", "cod": 200,
    },
    "NASA": {"date": "2026-03-02", "title": "The Crab Nebula from Hubble",
             "explanation": "A beautiful view of the Crab Nebula...", "media_type": "image"},
    "GitHub": {"current_user_url": "https://api.github.com/user",
               "repository_url": "https://api.github.com/repos/{owner}/{repo}"},
    "Twitter": {"data": [{"id": "123", "text": "Mock tweet about APIs"}], "meta": {"result_count": 1}},
    "Stripe": {"object": "list", "url": "/v1/charges", "has_more": False,
               "data": [{"id": "ch_mock", "amount": 2000, "currency": "usd", "status": "succeeded"}]},
    "Twilio": {"account_sid": "ACmock123", "status": "active", "type": "Full"},
    "SendGrid": {"status": "accepted", "message_id": "mock_msg_abc123"},
    "Spotify": {"playlists": {"items": [{"name": "Today's Top Hits", "id": "37i9dQZF1DXcBWIGoYBM5M"}]}},
    "Google Maps": {"results": [{"formatted_address": "1600 Amphitheatre Parkway, Mountain View, CA"}], "status": "OK"},
    "CoinGecko": {"gecko_says": "(V3) To the Moon!"},
    "Reddit": {"kind": "Listing", "data": {"children": [{"kind": "t3", "data": {"title": "Mock: API best practices", "score": 1523}}]}},
    "Slack": {"ok": True, "args": {"method": "api.test"}},
    "Discord": {"url": "wss://gateway.discord.gg"},
    "NewsAPI": {"status": "ok", "totalResults": 20, "articles": [{"title": "Mock: New API Standards", "source": {"name": "TechCrunch"}}]},
    "OpenAI": {"object": "list", "data": [{"id": "gpt-4o", "object": "model"}]},
}

CODE_TEMPLATES = {
    "python": '''"""
{use_case}
Generated by DevPulse (Mock/Offline Mode)
"""
import os, asyncio, httpx

async def main():
    api_key = os.getenv("API_KEY", "your-api-key-here")
    async with httpx.AsyncClient(timeout=30.0) as client:
        try:
            response = await client.get(
                "https://api.example.com/v1/data",
                headers={{"Authorization": f"Bearer {{api_key}}"}}
            )
            response.raise_for_status()
            return response.json()
        except httpx.HTTPError as e:
            print(f"API Error: {{e}}")
            return None

if __name__ == "__main__":
    asyncio.run(main())
''',
    "javascript": '''/**
 * {use_case}
 * Generated by DevPulse (Mock/Offline Mode)
 */
async function fetchData() {{
  try {{
    const response = await fetch('https://api.example.com/v1/data', {{
      headers: {{ 'Authorization': `Bearer ${{process.env.API_KEY}}` }},
    }});
    if (!response.ok) throw new Error(`HTTP ${{response.status}}`);
    return await response.json();
  }} catch (error) {{
    console.error('API Error:', error.message);
    return null;
  }}
}}
fetchData();
''',
    "typescript": '''/**
 * {use_case}
 * Generated by DevPulse (Mock/Offline Mode)
 */
interface ApiResponse {{
  data: unknown;
  status: string;
}}

async function fetchData(): Promise<ApiResponse | null> {{
  try {{
    const response = await fetch('https://api.example.com/v1/data', {{
      headers: {{ Authorization: `Bearer ${{process.env.API_KEY}}` }},
    }});
    if (!response.ok) throw new Error(`HTTP ${{response.status}}`);
    return (await response.json()) as ApiResponse;
  }} catch (error) {{
    console.error('API Error:', (error as Error).message);
    return null;
  }}
}}
''',
}


def get_mock_response(api_name: str, randomize: bool = True) -> Dict[str, Any]:
    """Get a mock response for an API."""
    base = MOCK_RESPONSES.get(api_name)
    if not base:
        return {"status": "ok", "message": f"Mock response for {api_name}", "data": {}}
    response = json.loads(json.dumps(base))
    if randomize and api_name == "OpenWeatherMap":
        response["main"]["temp"] = round(280 + random.random() * 15, 2)
        response["main"]["humidity"] = random.randint(40, 95)
    return {
        "status": "ok", "api_name": api_name, "mock": True,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "latency_ms": round(random.uniform(5, 50), 2),
        "data": response,
    }


def get_all_mock_responses() -> Dict[str, Any]:
    return {name: get_mock_response(name) for name in MOCK_RESPONSES}


def generate_mock_code(use_case: str, language: str = "python") -> Dict[str, Any]:
    """Generate code in offline mode (no AI API calls)."""
    template = CODE_TEMPLATES.get(language, CODE_TEMPLATES["python"])
    code = template.replace("{use_case}", use_case)
    return {
        "code": code, "language": language, "apis_used": ["example-api"],
        "tokens_used": 0, "status": "success",
        "message": "Generated in offline/mock mode (no AI API calls used)", "mock": True,
        "validation": {"is_valid": True, "score": 80, "grade": "B",
                        "passed_checks": ["has_async", "has_error_handling", "has_env_vars"],
                        "failed_checks": [], "suggestions": ["Replace mock URLs with real API endpoints"]},
    }
